name: chmod

on:
  push:
    branches: [ main, master ]  # 根据你的默认分支名称修改

jobs:
  set-script-permissions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取所有历史记录，确保权限变更可正确提交

    - name: Find and set execute permissions for scripts
      run: |
        # 定义需要设置执行权限的脚本文件模式
        find . -type f -name "*.sh" -exec chmod 755 {} \; || true
        find . -type f -name "*.py" -exec chmod 755 {} \; || true
        find . -type f -name "*.pl" -exec chmod 755 {} \; || true
        find . -type f -name "*.rb" -exec chmod 755 {} \; || true
        find . -type f -name "*.js" -exec chmod 755 {} \; || true
        # 添加其他你需要的脚本类型

    - name: Update file permissions in Git index
      run: |
        # 更新Git索引中的文件权限
        for file in $(find . -type f \( -name "*.sh" -o -name "*.py" -o -name "*.pl" -o -name "*.rb" -o -name "*.js" \)); do
          if [ -x "$file" ]; then
            git update-index --chmod=+x "$file"
          fi
        done

    - name: Check for permission changes
      id: check-permissions
      run: |
        # 检查是否有权限变更需要提交
        if ! git diff --cached --quiet; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push permission changes
      if: steps.check-permissions.outputs.has_changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "chore: set execute permissions for script files"
        git push
